version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/go/src/app
    depends_on:
      - db
  db:
    container_name: db
    platform: linux/x86_64 # M1チップ対応
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./data/my.cnf:/etc/mysql/my.cnf
      - ./data/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'